---
- name: General Config

  hosts: routers

  tasks:

  - name: Add Banner

    cisco.ios.ios_banner module:
      banner: login
      text: |
        cISCO 123456
      state: present

  - name: Merge provided configuration with device configuration
    ios_interfaces:
      config:
        - name: GigabitEthernet2
          description: Configured and Merged by Ansible Network
          enabled: true
