                                                         
---
- name: General Config

  hosts: routers

  tasks:

  - name: Add Banner

    cisco.ios.ios_banner:
      banner: login
      text: |
        Blannier is the king
      state: present
